version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 16...
      - npm install
      - echo Installing Yarn...
      - npm install --global yarn
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn install
  build:
    commands:
      - echo Building...
      - yarn build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build



#   {
#     "Version": "2012-10-17",
#     "Statement": [
#         {
#             "Sid": "PublicReadGetObject",
#             "Effect": "Allow",
#             "Principal": "*",
#             "Action": "s3:GetObject",
#             "Resource": "arn:aws:s3:::gradinfo-app/*"
#         }
#     ]
# }


# [
#     {
#         "AllowedHeaders": [
#             "*"
#         ],
#         "AllowedMethods": [
#             "GET",
#             "POST"
#         ],
#         "AllowedOrigins": [
#             "*"
#         ],
#         "ExposeHeaders": []
#     }
# ]